function ioi11
% Toolbox wrapper to call mctools functions

rev = '$Rev: 1 $';

SPMid = spm('FnBanner',mfilename,rev);
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','IOI11');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','ioi11.man','',Fgraph,'IOI11');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
    'Label',	'IOI11',...
    'Separator',	'on',...
    'Tag',		'IOI',...
    'HandleVisibility','on');

h01 = uimenu(h0,...
	'Label',	'Shrink specific colors',...
	'Separator',	'off',...
	'Tag',		'Shrink specific colors',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.shrink1'');',...
	'HandleVisibility','on');

h1  = uimenu(h0,...
	'Label',	'Read multispectral IOI data, old, non-interlaced format',...
	'Separator',	'off',...
	'Tag',		'Read multispectral IOI data, old, non-interlaced format',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.msioi1'');',...
	'HandleVisibility','on');

h1b  = uimenu(h0,...
	'Label',	'Read multispectral IOI data, new, interlaced format',...
	'Separator',	'off',...
	'Tag',		'Read multispectral IOI data, new, interlaced format',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.msread1'');',...
	'HandleVisibility','on');

h2  = uimenu(h0,...
	'Label',	'Compute Concentrations',...
	'Separator',	'off',...
	'Tag',		'Compute Concentrations',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.conc1'');',...
	'HandleVisibility','on');

h3  = uimenu(h0,...
	'Label',	'Compute Flow',...
	'Separator',	'off',...
	'Tag',		'Compute Flow',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.flow1'');',...
	'HandleVisibility','on');

% h31  = uimenu(h0,...
% 	'Label',	'Extract electrophysiology',...
% 	'Separator',	'off',...
% 	'Tag',		'Extract electrophysiology',...
%     'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.electro1'');',...
% 	'HandleVisibility','on');
% 
h4  = uimenu(h0,...
	'Label',	'Select ROI',...
	'Separator',	'off',...
	'Tag',		'Select ROI',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.create_roi1'');',...
	'HandleVisibility','on');

h5  = uimenu(h0,...
	'Label',	'Extract ROI',...
	'Separator',	'off',...
	'Tag',		'Extract ROI',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.extract_roi1'');',...
	'HandleVisibility','on');

h6  = uimenu(h0,...
	'Label',	'Average stimulations',...
	'Separator',	'off',...
	'Tag',		'Average stimulations',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.stim_mean1'');',...
	'HandleVisibility','on');

h7  = uimenu(h0,...
	'Label',	'GLM on ROIs',...
	'Separator',	'off',...
	'Tag',		'GLM on ROIs',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.ioi11.glm_roi1'');',...
	'HandleVisibility','on');

